### ISSUE TITLE
Details about caluculating the fraction of the genome altered

### ISSUE THREAD

**Issue by Cacti-Jiang** [dpeerlab/SCLC_atlas-HTAN#2]
Hi，
I am wondering how to calculate the fraction of the genome changed with infercnv? Specifically, were copy number changes mentioned in the article based on the residual expression or HMM predictions? Thanks!

**Comment by jmchan88** [comment]
Hey there, 

For CNV inference in this project, we just used the sliding window approach, using a window length of 200 genes (not the HMM that the latest version of inferCNV has added). Using the resulting copy number profile, we called copy number change for any deviations of at least 2 standard deviations away from the diploid mean, where the diploid mean is defined by the normal lung samples in our cohort. We calculated the fraction of the genome affected by these final copy number calls to serve as a per-cell summary score of CNV burden. Let me know if there are any remaining q's!

Joe

**Comment by Cacti-Jiang** [comment]
Hi Joe,
Thanks for the speedy responses! Would you mind showing me the version of infercnv used in the analysis? Moreover, was the copy number profile mentioned above derived from the output file "expr.infercnv.dat"?

**Comment by jmchan88** [comment]
Apologies for the delay in subsequent response! So in particular, we implement our own version of the sliding window approach (referring to the original inferCNV algorithm). I've posted the scripts for calculating copy number changes in the "scripts" folder. I'll post the corresponding CNV profiles as soon as possible.

**Comment by Cacti-Jiang** [comment]
Thanks Joe! This really helped us a lot!
